dist: xenial
language: python
install:
  - sudo apt-get install -y --force-yes python-virtualenv
  - virtualenv $HOME/venv && source $HOME/venv/bin/activate
  - pip install ansible-lint
script:
  - ansible-lint main.yml
