---
dist: xenial
language: python
install:
  - sudo apt-get install -y --force-yes python-virtualenv
  - virtualenv $HOME/env && source $HOME/env/bin/activate
  - pip install ansible-lint yamllint
script:
  - ansible-lint main.yml
  - "yamllint -c .yamllint ."
...
