- src: https://github.com/vdombrovski/ansible-role-prometheus
  version: master
- src: https://github.com/vdombrovski/ansible-role-openio-netdata
  version: prometheus
- src: https://github.com/vdombrovski/ansible-role-openio-grafana
  version: prometheus
- src: https://github.com/shelleg/ansible-role-ntp
  version: master
