---
- src: https://github.com/open-io/ansible-role-openio-repository
  version: 0922a46c1b2dcf779111057f960f481965b6c960
- src: https://github.com/open-io/ansible-role-openio-prometheus
  version: 3.1.1
- src: https://github.com/open-io/ansible-role-openio-netdata
  version: 1.1.8
- src: https://github.com/open-io/ansible-role-openio-grafana
  version: 2.1.3
- src: https://github.com/geerlingguy/ansible-role-ntp
  version: master
- src: https://github.com/cloudalchemy/ansible-blackbox-exporter
  version: 0.5.11
- src: https://github.com/cloudalchemy/ansible-alertmanager
  version: 0.12.0
...
