---
- src: https://github.com/open-io/ansible-role-openio-repository
  version: 4bded6650dd6801743bb7fc2deae336515264e4c
- src: https://github.com/open-io/ansible-role-prometheus
  version: 3.0.2
- src: https://github.com/open-io/ansible-role-openio-netdata
  version: 1.1.7
- src: https://github.com/open-io/ansible-role-openio-grafana
  version: 2.0.4
- src: https://github.com/geerlingguy/ansible-role-ntp
  version: master
...
