---
- hosts: openio:admin
  become: true
  roles:
    - ansible-blackbox-exporter
  vars:
    blackbox_exporter_version: 0.12.0
    blackbox_exporter_root_dir: /usr/bin/blackbox_exporter
    blackbox_exporter_web_listen_address: 0.0.0.0:9115
    blackbox_exporter_configuration_modules:
      tcpcheck: { prober: tcp, timeout: 5s }
      icmpcheck: { prober: icmp, timeout: 5s, icmp: { preferred_ip_protocol: "ip4" } }
      oioping:
        prober: tcp
        timeout: 5s
        tcp:
          query_response:
            # REQ FORMAT: \x00\x00\x0000.\x80 00000000000000000000000000000000\x81\x08REQ_PING\xa3\x0
            - send: !!binary AAAAMDAugCAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMIEIUkVRX1BJTkejAAo=
            - expect: ".*OK.*"
      meta0:
        prober: http
        timeout: 5s
      meta1:
        prober: http
        timeout: 5s
      meta2:
        prober: http
        timeout: 5s
      rawx:
        prober: http
        timeout: 5s
      oioproxy:
        prober: http
        timeout: 5s
      account:
        prober: http
        timeout: 5s
      conscience:
        prober: http
        timeout: 5s
      zookeeper:
        prober: tcp
        timeout: 5s
        tcp:
          query_response:
            - send: "ruok"
            - expect: "imok"
      redis:
        prober: tcp
        timeout: 5s
        tcp:
          query_response:
            - send: "PING"
            - expect: "PONG"
      redissentinel:
        prober: tcp
        timeout: 5s
        tcp:
          query_response:
            - send: "PING"
            - expect: "PONG"
      beanstalkd:
        prober: tcp
        timeout: 5s
        tcp:
          query_response:
            - send: "stats\r\n"
            - expect: "OK.*"
      rdir:
        prober: http
        timeout: 5s

- name: Install prometheus
  hosts: all
  become: true
  gather_facts: true
  vars:
    openio_monitoring_netdata_group: openio
    openio_monitoring_netdata_port: 19999
    openio_monitoring_iface: ens3
    prometheus_monitored_group: openio
    prometheus_monitored_iface: ens3
    prometheus_admin_group: admin
    prometheus_admin_iface: ens3
    prometheus_blackbox_zk_port_regex: "^(60)[0-9]+$"
    prometheus_alert_sla_default_medium: 67
    prometheus_alert_sla_default_high: 34
  roles:
    - role: ansible-role-ntp
    - role: ansible-role-prometheus
      prometheus_storage_local_path: "/var/lib/prometheus/data"
      prometheus_recording_rules:
        - name: netdata_aggregation
          interval: 10s
          rules:
            - record: "aggr:netdata_openio_score:avg_per_service"
              expr: "avg(label_replace(netdata_openio_score__average,\
                     \"dim2\", \"$1\", \"dimension\", \"(.*?)[_].*\")) by (dim2)"
      prometheus_jobs:
        - name: netdata
          metrics_path: "/api/v1/allmetrics"
          scrape_interval: 10s
          targets: "[{% for host in groups[openio_monitoring_netdata_group] -%}
                         \"{{ hostvars[host]['ansible_' + openio_monitoring_iface]['ipv4']['address'] +
                              ':' + (openio_monitoring_netdata_port | string) }}\"{% if not loop.last %},{% endif %}
                   {%- endfor %}]"
      prometheus_components:
        - prometheus
...
