---
- name: Update components monitored by blackbox
  hosts: all
  become: true
  gather_facts: true
  vars:
    openio_monitoring_netdata_group: openio
    openio_monitoring_netdata_port: 19999
    openio_monitoring_iface: ens3
    prometheus_monitored_group: openio
    prometheus_monitored_iface: ens3
    prometheus_admin_group: admin
    prometheus_admin_iface: ens3
    prometheus_blackbox_zk_port_regex: "^(60)[0-9]+$"
    prometheus_alert_sla_default_medium: 67
    prometheus_alert_sla_default_high: 34
  roles:
    - role: ansible-role-prometheus
      prometheus_storage_local_path: "/var/lib/prometheus/data"
      prometheus_install: false
      prometheus_blackbox_update: true
      prometheus_components:
        - prometheus
...
