---
- hosts: openio
  become: true
  roles:
    - ansible-blackbox-exporter
  vars:
    blackbox_exporter_version: 0.12.0
    blackbox_exporter_root_dir: /usr/bin/blackbox_exporter
    blackbox_exporter_web_listen_address: 0.0.0.0:9115
    blackbox_exporter_configuration_modules:
      tcpcheck: { prober: tcp, timeout: 5s }
      icmp: { prober: icmp, timeout: 5s, icmp: { preferred_ip_protocol: "ip4" } }
      oioping:
        prober: tcp
        timeout: 5s
        tcp:
          query_response:
            # REQ FORMAT: \x00\x00\x0000.\x80 00000000000000000000000000000000\x81\x08REQ_PING\xa3\x0
            - send: !!binary AAAAMDAugCAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMIEIUkVRX1BJTkejAAo=
            - expect: ".*OK.*"
      metax:
        prober: http
        timeout: 5s
      rawx:
        prober: http
        timeout: 5s
      oioproxy:
        prober: http
        timeout: 5s
      account:
        prober: http
        timeout: 5s
      zookeeper:
        prober: tcp
        timeout: 5s
        tcp:
          query_response:
            - send: "ruok"
            - expect: "imok"
...
