---
- name: Install repository
<<<<<<< HEAD
  hosts: openio
=======
  hosts: netdata
>>>>>>> WIP: Rework for alert support
  become: true
  gather_facts: true
  roles:
    - role: ansible-role-openio-repository

- name: Install netdata on monitored nodes
  hosts: netdata
  become: true
  gather_facts: true
  roles:
    - role: ansible-role-openio-netdata
<<<<<<< HEAD
      openio_netdata_namespace: "OPENIO"
      openio_netdata_bind_address: 0.0.0.0
      openio_netdata_bind_port: 19999
      openio_netdata_oio_plugins:
        - name: openio
          enabled: true
          every: 10
          opts: ""
        - name: zookeeper
          enabled: true
          every: 10
          opts: ""
        - name: container
          enabled: true
          every: 10
          opts: "--fast"
      openio_netdata_oio_container_plugin_target: "{{ hostvars[ansible_play_hosts[0]]['ansible_hostname'] }}"
=======
>>>>>>> WIP: Rework for alert support

- name: Install blackbox
  hosts: blackbox:admin
  become: true
  gather_facts: true
  roles:
    - ansible-blackbox-exporter

- name: Install prometheus
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: ansible-role-openio-prometheus

- name: Install alertmanager
  hosts: alertmanager
  become: true
  gather_facts: true
  roles:
    - role: ansible-alertmanager

- name: Install NTP server
  hosts: prometheus
  become: true
  gather_facts: true
  roles:
    - role: ansible-role-ntp
<<<<<<< HEAD
    - role: ansible-role-prometheus
      prometheus_storage_local_path: "/var/lib/prometheus/data"
      prometheus_jobs:
        - name: netdata
          metrics_path: "/api/v1/allmetrics"
          scrape_interval: 10s
          targets: "[{% for host in groups[openio_monitoring_netdata_group] -%}
                         \"{{ hostvars[host]['ansible_' + openio_monitoring_iface]['ipv4']['address'] +
                              ':' + (openio_monitoring_netdata_port | string) }}\"{% if not loop.last %},{% endif %}
                   {%- endfor %}]"
      prometheus_components:
        - prometheus
=======

- name: Install grafana
  hosts: grafana
  become: true
  gather_facts: true
  roles:
>>>>>>> WIP: Rework for alert support
    - role: ansible-role-openio-grafana
...
