---
- name: Install and configure the monitoring stack
  hosts: openio
  become : true
  gather_facts: true
  roles:
    - role: ansible-role-openio-netdata
      netdata_backend_enabled: true
      netdata_backend_destination: "{{ hostvars[ groups['admin'][0] ]['ansible_host'] }}"

- name: Install monitoring on admin machine
  hosts: admin
  become: true
  gather_facts: true
  roles:
    - role: ansible-role-openio-influxdb 
    - role: ansible-role-openio-grafana
      grafana_dashboard:
        host_regex: "/.*/"
        namespace: OPENIO
        group: openio
      grafana_auth:
        user: admin
        password: admin
