---
- name: Install netdata on monitored nodes
  hosts: openio
  become : true
  gather_facts: true
  roles:
    - role: ansible-role-openio-netdata
      netdata_backend_enabled: true
      netdata_backend_destination: "{{ hostvars[ groups['admin'][0] ]['ansible_host'] }}"
      netdata_backend_update_every: 30
      # Specify hostname of the machine that will hold container.plugin
      netdata_container_plugin_host: node1
      netdata_openio_plugins:
      - name: openio
        enabled: true
        opts: "--ns OPENIO"
      - name: zookeeper
        enabled: true
        opts: "--ns OPENIO"
      - name: container
        enabled: true
        every: 120
        opts: "--threshold 0 --limit 1000"

- name: Install prometheus and grafana on admin machine
  hosts: admin
  become: true
  gather_facts: true
  roles:
    - role: ansible-role-ntp
    - role: ansible-role-prometheus
      prometheus_components:
        - prometheus
      prometheus_jobs:
        - name: netdata
          metrics_path: "/api/v1/allmetrics"
          # List of targets
          targets: "[{% for host in groups['openio'] -%}
                         \"{{ hostvars[host]['ansible_host']+':19999' }}\"{% if not loop.last %},{% endif %}
                   {%- endfor %}]"
      prometheus_recording_rules:
        - name: netdata_aggregation
          interval: 10s
          rules:
            - record: "aggr:netdata_openio_score:avg_per_service"
              expr: "avg(label_replace(netdata_openio_score__average, \"dim2\", \"$1\", \"dimension\", \"(.*?)[_].*\")) by (dim2)"
    - role: ansible-role-openio-grafana
      grafana_auth:
        user: admin
        password: admin
