---
- name: Install repository
  hosts: openio
  become: true
  gather_facts: true
  roles:
    - role: ansible-role-openio-repository

- name: Install netdata on monitored nodes
  hosts: netdata
  become: true
  gather_facts: true
  roles:
    - role: ansible-role-openio-netdata

- name: Install blackbox
  hosts: blackbox
  become: true
  gather_facts: true
  roles:
    - ansible-blackbox-exporter

- name: Install prometheus
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: ansible-role-openio-prometheus

- name: Install alertmanager
  hosts: alertmanager
  become: true
  gather_facts: true
  roles:
    - role: cloudalchemy.alertmanager

- name: Install NTP server
  hosts: prometheus
  become: true
  gather_facts: true
  roles:
    - role: ansible-role-ntp

- name: Install grafana
  hosts: grafana
  become: true
  gather_facts: true
  roles:
    - role: ansible-role-openio-grafana
...
