---
- name: Install netdata on monitored nodes
  hosts: openio
  become: true
  gather_facts: true
  roles:
    - role: ansible-role-openio-netdata
      openio_netdata_namespace: "OPENIO"
      openio_netdata_inventory_groupname: openio
      openio_netdata_bind_address: 0.0.0.0
      openio_netdata_bind_port: 19999
      openio_netdata_oio_plugins:
        - name: openio
          enabled: true
          every: 10
          opts: ""
        - name: zookeeper
          enabled: true
          every: 10
          opts: ""
        - name: container
          enabled: true
          every: 120
          opts: "--threshold 0 --limit 1000"
      openio_netdata_oio_container_plugin_target: "{{ hostvars[ansible_play_hosts[0]]['ansible_hostname'] }}"

- name: Install prometheus and grafana on admin machine
  hosts: admin
  become: true
  gather_facts: true
  vars:
    openio_monitoring_netdata_group: openio
    openio_monitoring_netdata_port: 19999
    openio_monitoring_iface: eth0
  roles:
    - role: ansible-role-ntp
    - role: ansible-role-prometheus
      prometheus_storage_local_path: "/var/lib/prometheus/data"
      prometheus_recording_rules:
        - name: netdata_aggregation
          interval: 10s
          rules:
            - record: "aggr:netdata_openio_score:avg_per_service"
              expr: "avg(label_replace(netdata_openio_score__average,\
                     \"dim2\", \"$1\", \"dimension\", \"(.*?)[_].*\")) by (dim2)"
      prometheus_jobs:
        - name: netdata
          metrics_path: "/api/v1/allmetrics"
          scrape_interval: 10s
          targets: "[{% for host in groups[openio_monitoring_netdata_group] -%}
                         \"{{ hostvars[host]['ansible_' + openio_monitoring_iface]['ipv4']['address'] +
                              ':' + (openio_monitoring_netdata_port | string) }}\"{% if not loop.last %},{% endif %}
                   {%- endfor %}]"
      prometheus_components:
        - prometheus
    - role: ansible-role-openio-grafana
      grafana_auth:
        user: admin
        password: admin
...
