---
grafana_theme: light

prometheus_host: "{{ hostvars[inventory_hostname]['ansible_' +\
  prometheus_default_admin_iface]['ipv4']['address'] }}"
prometheus_port: "{{ prometheus_listen_port }}"

grafana_http:
  protocol: http
  host: "{{ hostvars[inventory_hostname]['ansible_' +\
    prometheus_default_admin_iface]['ipv4']['address'] }}"
  port: 3000
  domain: localhost
...
