---
openio_netdata_bind_address: "{{ hostvars['ansible_' + prometheus_default_admin_iface]['ipv4']['address'] }}"
openio_netdata_bind_port: 19999
openio_netdata_oio_plugins:
  - name: openio
    enabled: true
    every: 10
    opts: ""
  - name: zookeeper
    enabled: true
    every: 10
    opts: ""
  - name: container
    enabled: true
    every: 10
    opts: "--fast"
...
