---
# Global
prometheus_blackbox_group: blackbox
prometheus_admin_group: admin
prometheus_netdata_group: netdata
prometheus_alertmanager_group: alertmanager

prometheus_listen_ip: 0.0.0.0
prometheus_listen_port: 9090
prometheus_storage_retention: "10y"
prometheus_loglevel: info
prometheus_user: prometheus
prometheus_group: prometheus
prometheus_version: 2.2.1

# Directories
prometheus_storage_path: /var/lib/prometheus/data
prometheus_conf_dir: /etc/prometheus

# Collection: netdata
prometheus_netdata_enabled: true
prometheus_netdata_interval: 10s
prometheus_netdata_iface: eth0
prometheus_netdata_port: 19999
prometheus_netdata_targets: "[{% for host in groups[prometheus_netdata_group] -%}
\"{{ hostvars[host]['ansible_' + prometheus_netdata_iface]['ipv4']['address'] +
':' + (prometheus_netdata_port | string) }}\"{% if not loop.last %},{% endif %}
 {%- endfor %}]"

# Collection: blackbox
prometheus_blackbox_enabled: true
prometheus_blackbox_interval: 10s
prometheus_blackbox_zk_port_regex: "^(60)[0-9]+$"
prometheus_blackbox_port: 9115
prometheus_blackbox_iface: eth0
prometheus_blackbox_admin_iface: eth0

# Alert generation
prometheus_alert_sla_default_medium: 67
prometheus_alert_sla_levels_medium: {}
prometheus_alert_instance_default_medium: 67
prometheus_alert_instance_levels_medium: {}

prometheus_alert_sla_default_high: 34
prometheus_alert_sla_levels_high: {}
prometheus_alert_instance_default_high: 34
prometheus_alert_instance_levels_high: {}

# Alert forwarding
prometheus_alertmanager_enabled: true
prometheus_alertmanager_iface: eth0
prometheus_alertmanager_port: 9093
prometheus_alertmanager_interval: 10s
prometheus_alertmanager_host: "{{ hostvars[groups[prometheus_netdata_group][0]]\
  ['ansible_' + prometheus_alertmanager_iface]['ipv4']['address'] }}"
...
