---
prometheus_blackbox_group: blackbox
prometheus_admin_group: admin
prometheus_netdata_group: netdata
prometheus_alertmanager_group: alertmanager

prometheus_listen_ip: "{{ hostvars['ansible_' + prometheus_default_admin_iface]['ipv4']['address'] }}"
prometheus_listen_port: 9090
prometheus_storage_retention: "10y"
prometheus_loglevel: info
prometheus_user: prometheus
prometheus_group: prometheus
prometheus_version: 2.2.1

prometheus_conf_dir: /etc/prometheus

prometheus_netdata_enabled: true
prometheus_netdata_iface: "{{ prometheus_default_node_iface }}"
prometheus_netdata_interval: "{{ prometheus_default_collection_interval }}"
prometheus_netdata_port: 19999
prometheus_netdata_targets: “{{ groups[prometheus_netdata_group] \
   | map(‘extract’, hostvars, [‘ansible_’ + prometheus_netdata_iface, ‘ipv4’, ‘address’])\
   | join(‘:’ + prometheus_netdata_port + ',') }}:{{prometheus_netdata_port}}"

# Collection: blackbox
prometheus_blackbox_enabled: true
prometheus_blackbox_port: 9115
prometheus_blackbox_zk_port_regex: "^(60)[0-9]+$"
prometheus_blackbox_interval: "{{ prometheus_default_collection_interval }}"
prometheus_blackbox_iface: "{{ prometheus_default_node_iface }}"
prometheus_blackbox_admin_iface: "{{ prometheus_default_admin_iface }}"

# Alert generation
prometheus_alert_sla_default_medium: 67
prometheus_alert_sla_levels_medium: {}
prometheus_alert_instance_default_medium: 67
prometheus_alert_instance_levels_medium: {}

prometheus_alert_sla_default_high: 34
prometheus_alert_sla_levels_high: {}
prometheus_alert_instance_default_high: 34
prometheus_alert_instance_levels_high: {}

# Alert forwarding
prometheus_alertmanager_enabled: true
prometheus_alertmanager_iface: "{{ prometheus_default_admin_iface }}"
prometheus_alertmanager_interval: "{{ prometheus_default_collection_interval }}"
prometheus_alertmanager_port: 9093
prometheus_alertmanager_host: "{{ hostvars[groups[prometheus_alertmanager_group][0]]\
  ['ansible_' + prometheus_alertmanager_iface]['ipv4']['address'] }}"
...
